### ISSUE TITLE
Exciting compile error

### ISSUE THREAD

**Issue by AtlanticBit** [shinyquagsire23/bootstrap#4]
/Users/brunoturek/devkitPro/devkitARM/bin/../lib/gcc/arm-none-eabi/4.9.2/../../../../arm-none-eabi/bin/ld: error: bootstrap.o uses VFP register arguments, /Users/brunoturek/ciaelf/output/Loadboot.elf.elf does not
/Users/brunoturek/devkitPro/devkitARM/bin/../lib/gcc/arm-none-eabi/4.9.2/../../../../arm-none-eabi/bin/ld: failed to merge target specific data of file bootstrap.o
/Users/brunoturek/devkitPro/devkitARM/bin/../lib/gcc/arm-none-eabi/4.9.2/../../../../arm-none-eabi/bin/ld: error: main.o uses VFP register arguments, /Users/brunoturek/ciaelf/output/Loadboot.elf.elf does not
/Users/brunoturek/devkitPro/devkitARM/bin/../lib/gcc/arm-none-eabi/4.9.2/../../../../arm-none-eabi/bin/ld: failed to merge target specific data of file main.o
main.o: In function `main':
/Users/brunoturek/ciaelf/source/main.c:37: undefined reference to`gfxInitDefault'
collect2: error: ld returned 1 exit status

so yeah

**Comment by AtlanticBit** [comment]
Using original makefile:
/Users/brunoturek/devkitPro/devkitARM/bin/../lib/gcc/arm-none-eabi/4.9.2/../../../../arm-none-eabi/bin/ld: error: bootstrap.o uses VFP register arguments, /Users/brunoturek/bootstrap/bootstrap.elf does not
/Users/brunoturek/devkitPro/devkitARM/bin/../lib/gcc/arm-none-eabi/4.9.2/../../../../arm-none-eabi/bin/ld: failed to merge target specific data of file bootstrap.o
/Users/brunoturek/devkitPro/devkitARM/bin/../lib/gcc/arm-none-eabi/4.9.2/../../../../arm-none-eabi/bin/ld: error: main.o uses VFP register arguments, /Users/brunoturek/bootstrap/bootstrap.elf does not
/Users/brunoturek/devkitPro/devkitARM/bin/../lib/gcc/arm-none-eabi/4.9.2/../../../../arm-none-eabi/bin/ld: failed to merge target specific data of file main.o
main.o: In function `main':
/Users/brunoturek/bootstrap/./main.c:37: undefined reference to`gfxInitDefault'
collect2: error: ld returned 1 exit status
make[1]: **\* [/Users/brunoturek/bootstrap/bootstrap.elf] Error 1
make: **\* [build] Error 2

**Comment by AtlanticBit** [comment]
nvm, changet -mfloat to soft in makefile

**Comment by dazjo** [comment]
http://devkitpro.org/viewtopic.php?f=13&t=8409

The proper fix is to update devkitARM, not revert the Makefile.
